DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'engram_service') THEN
    CREATE ROLE engram_service LOGIN
      PASSWORD 'REPLACE_WITH_STRONG_RANDOM_VALUE'
      BYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE postgres TO engram_service;
GRANT USAGE ON SCHEMA public TO engram_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO engram_service;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO engram_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO engram_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO engram_service;
