-- EC-47 — pass_runs observability columns.
--
-- Adds `durationMs` (precomputed wall-clock duration in ms) and a free-form
-- `metadata` JSONB column to `pass_runs`. Both are nullable so the change is
-- backward-compatible with rows written before EC-47 lands.
--
-- Generated by hand (prisma migrate dev --create-only could not run without
-- DATABASE_URL in this worker). Mirrors the SQL Prisma 6.19 emits for
-- additive Int/Json columns.

-- AlterTable
ALTER TABLE "pass_runs"
  ADD COLUMN "durationMs" INTEGER,
  ADD COLUMN "metadata"   JSONB;
