import { TopicDefinition } from './prefetch.types';

/**
 * Personal and professional topic definitions
 */
export const PERSONAL_TOPIC_DEFINITIONS: TopicDefinition[] = [
  {
    id: 'family',
    name: 'Family',
    description: 'Memories about family members and family life',
    keywords: ['wife', 'husband', 'daughter', 'son', 'kid', 'child', 'family'],
    prototypeQuery: 'family relationships spouse children parents home life',
    prefetchPriority: 8,
    defaultMemoryLimit: 30,
    decayRate: 0.1,
    relatedTopics: ['schedule', 'health', 'events'],
  },
  {
    id: 'family/immediate',
    parentId: 'family',
    name: 'Immediate Family',
    description: 'Spouse and children',
    keywords: ['wife', 'husband', 'daughter', 'son', 'spouse'],
    prototypeQuery: 'wife husband daughter son spouse child immediate family',
    prefetchPriority: 9,
    defaultMemoryLimit: 50,
    decayRate: 0.05,
    relatedTopics: ['family', 'schedule', 'health'],
  },
  {
    id: 'family/extended',
    parentId: 'family',
    name: 'Extended Family',
    description: 'Parents, siblings, and other relatives',
    keywords: ['mom', 'dad', 'mother', 'father', 'brother', 'sister'],
    prototypeQuery: 'parents siblings relatives extended family',
    prefetchPriority: 6,
    defaultMemoryLimit: 20,
    decayRate: 0.15,
    relatedTopics: ['family', 'events'],
  },
  {
    id: 'family/pets',
    parentId: 'family',
    name: 'Pets',
    description: 'Family pets and animals',
    keywords: ['dog', 'cat', 'pet', 'husky'],
    prototypeQuery: 'pet dog cat animal companion',
    prefetchPriority: 5,
    defaultMemoryLimit: 15,
    decayRate: 0.1,
    relatedTopics: ['family', 'health'],
  },

  // Professional
  {
    id: 'work',
    name: 'Work',
    description: 'Professional work context',
    keywords: ['work', 'job', 'office', 'meeting', 'project', 'deadline'],
    prototypeQuery: 'work job career professional office colleagues',
    prefetchPriority: 7,
    defaultMemoryLimit: 25,
    decayRate: 0.15,
    relatedTopics: ['projects', 'schedule', 'technical'],
  },
  {
    id: 'work/role',
    parentId: 'work',
    name: 'Current Role',
    description: 'Current job and responsibilities',
    keywords: ['role', 'job', 'position', 'responsibilities'],
    prototypeQuery: 'my role job position responsibilities duties',
    prefetchPriority: 6,
    defaultMemoryLimit: 15,
    decayRate: 0.1,
    relatedTopics: ['work', 'identity'],
  },
  {
    id: 'work/colleagues',
    parentId: 'work',
    name: 'Colleagues',
    description: 'People at work',
    keywords: ['colleague', 'coworker', 'teammate', 'boss', 'manager'],
    prototypeQuery: 'colleague coworker teammate work people',
    prefetchPriority: 5,
    defaultMemoryLimit: 20,
    decayRate: 0.2,
    relatedTopics: ['work', 'events/meetings'],
  },
  {
    id: 'projects',
    name: 'Projects',
    description: 'Projects and initiatives',
    keywords: ['project', 'initiative', 'build', 'develop'],
    prototypeQuery: 'project building developing creating initiative',
    prefetchPriority: 7,
    defaultMemoryLimit: 30,
    decayRate: 0.15,
    relatedTopics: ['work', 'technical'],
  },
  {
    id: 'projects/active',
    parentId: 'projects',
    name: 'Active Projects',
    description: 'Currently active projects',
    keywords: ['current', 'working on', 'building', 'developing'],
    prototypeQuery: 'current project active building developing feature',
    prefetchPriority: 8,
    defaultMemoryLimit: 40,
    decayRate: 0.2,
    relatedTopics: ['work', 'technical', 'schedule'],
  },
  {
    id: 'projects/completed',
    parentId: 'projects',
    name: 'Completed Projects',
    description: 'Past completed projects',
    keywords: ['completed', 'finished', 'shipped', 'launched'],
    prototypeQuery: 'completed finished shipped launched past project',
    prefetchPriority: 4,
    defaultMemoryLimit: 15,
    decayRate: 0.25,
    relatedTopics: ['projects', 'history'],
  },
  {
    id: 'technical',
    name: 'Technical',
    description: 'Engineering and technical topics',
    keywords: ['code', 'api', 'database', 'deploy', 'bug', 'feature'],
    prototypeQuery: 'code programming engineering technical development api',
    prefetchPriority: 7,
    defaultMemoryLimit: 30,
    decayRate: 0.2,
    relatedTopics: ['projects/active', 'work', 'agent/learnings'],
  },
  {
    id: 'technical/skills',
    parentId: 'technical',
    name: 'Technical Skills',
    description: 'Programming languages and skills',
    keywords: ['skill', 'language', 'framework', 'expertise'],
    prototypeQuery: 'programming skill language framework expertise',
    prefetchPriority: 5,
    defaultMemoryLimit: 20,
    decayRate: 0.1,
    relatedTopics: ['technical', 'identity'],
  },
  {
    id: 'technical/tools',
    parentId: 'technical',
    name: 'Tools',
    description: 'Development tools and services',
    keywords: ['tool', 'service', 'platform', 'ide'],
    prototypeQuery: 'tool service platform development environment',
    prefetchPriority: 4,
    defaultMemoryLimit: 15,
    decayRate: 0.2,
    relatedTopics: ['technical'],
  },

  // Temporal
  {
    id: 'schedule',
    name: 'Schedule',
    description: 'Calendar, appointments, and time-based events',
    keywords: ['today', 'tomorrow', 'meeting', 'appointment', 'calendar'],
    prototypeQuery: 'schedule calendar meeting appointment today tomorrow',
    prefetchPriority: 9,
    defaultMemoryLimit: 20,
    decayRate: 0.3,
    relatedTopics: ['work', 'events', 'family'],
  },
  {
    id: 'schedule/today',
    parentId: 'schedule',
    name: 'Today',
    description: "Today's schedule",
    keywords: ['today', 'this morning', 'this afternoon', 'tonight'],
    prototypeQuery: 'today schedule plans morning afternoon',
    prefetchPriority: 10,
    defaultMemoryLimit: 15,
    decayRate: 0.5,
    relatedTopics: ['schedule', 'events/meetings'],
  },
  {
    id: 'schedule/week',
    parentId: 'schedule',
    name: 'This Week',
    description: "This week's schedule",
    keywords: ['this week', 'next week', 'weekly'],
    prototypeQuery: 'week weekly schedule plans upcoming',
    prefetchPriority: 8,
    defaultMemoryLimit: 20,
    decayRate: 0.4,
    relatedTopics: ['schedule', 'events'],
  },
  {
    id: 'schedule/upcoming',
    parentId: 'schedule',
    name: 'Upcoming',
    description: 'Future schedule and plans',
    keywords: ['upcoming', 'future', 'planned', 'scheduled'],
    prototypeQuery: 'upcoming future planned scheduled soon',
    prefetchPriority: 7,
    defaultMemoryLimit: 15,
    decayRate: 0.3,
    relatedTopics: ['schedule', 'events'],
  },
  {
    id: 'history',
    name: 'History',
    description: 'Past events and memories',
    keywords: ['past', 'history', 'before', 'previously'],
    prototypeQuery: 'past history before previously remembered',
    prefetchPriority: 4,
    defaultMemoryLimit: 20,
    decayRate: 0.1,
    relatedTopics: ['conversation'],
  },
  {
    id: 'history/recent',
    parentId: 'history',
    name: 'Recent History',
    description: 'Recent past events',
    keywords: ['recently', 'last week', 'few days ago'],
    prototypeQuery: 'recently last week few days ago recent',
    prefetchPriority: 5,
    defaultMemoryLimit: 25,
    decayRate: 0.2,
    relatedTopics: ['history', 'conversation'],
  },
  {
    id: 'events',
    name: 'Events',
    description: 'Events and occasions',
    keywords: ['event', 'meeting', 'conference', 'birthday'],
    prototypeQuery: 'event meeting conference birthday celebration',
    prefetchPriority: 6,
    defaultMemoryLimit: 20,
    decayRate: 0.2,
    relatedTopics: ['schedule', 'family', 'work'],
  },
  {
    id: 'events/meetings',
    parentId: 'events',
    name: 'Meetings',
    description: 'Work meetings and calls',
    keywords: ['meeting', 'standup', 'sync', 'call'],
    prototypeQuery: 'meeting standup sync call video conference',
    prefetchPriority: 7,
    defaultMemoryLimit: 20,
    decayRate: 0.3,
    relatedTopics: ['events', 'work', 'schedule'],
  },
  {
    id: 'events/deadlines',
    parentId: 'events',
    name: 'Deadlines',
    description: 'Deadlines and due dates',
    keywords: ['deadline', 'due date', 'deliverable'],
    prototypeQuery: 'deadline due date deliverable submission milestone',
    prefetchPriority: 8,
    defaultMemoryLimit: 15,
    decayRate: 0.4,
    relatedTopics: ['events', 'projects', 'schedule'],
  },

];
