import { TopicDefinition } from './prefetch.types';

/**
 * System, health, and identity topic definitions
 */
export const SYSTEM_TOPIC_DEFINITIONS: TopicDefinition[] = [
  {
    id: 'health',
    name: 'Health',
    description: 'Physical and mental health topics',
    keywords: ['health', 'exercise', 'doctor', 'sick', 'workout', 'sleep'],
    prototypeQuery: 'health wellness exercise medical doctor symptoms',
    prefetchPriority: 6,
    defaultMemoryLimit: 20,
    decayRate: 0.15,
    relatedTopics: ['preferences', 'schedule'],
  },
  {
    id: 'health/physical',
    parentId: 'health',
    name: 'Physical Health',
    description: 'Exercise, diet, and physical wellness',
    keywords: ['exercise', 'workout', 'diet', 'fitness'],
    prototypeQuery: 'exercise workout fitness diet physical health',
    prefetchPriority: 5,
    defaultMemoryLimit: 15,
    decayRate: 0.15,
    relatedTopics: ['health', 'preferences'],
  },
  {
    id: 'health/mental',
    parentId: 'health',
    name: 'Mental Health',
    description: 'Mental wellness and emotional health',
    keywords: ['stress', 'anxiety', 'mental', 'therapy'],
    prototypeQuery: 'mental health stress anxiety therapy wellness',
    prefetchPriority: 7,
    defaultMemoryLimit: 15,
    decayRate: 0.1,
    relatedTopics: ['health', 'identity'],
  },
  {
    id: 'health/medical',
    parentId: 'health',
    name: 'Medical',
    description: 'Medical conditions and treatments',
    keywords: ['doctor', 'hospital', 'medication', 'treatment'],
    prototypeQuery: 'doctor hospital medical condition treatment',
    prefetchPriority: 6,
    defaultMemoryLimit: 15,
    decayRate: 0.1,
    relatedTopics: ['health', 'schedule'],
  },

  // Preferences
  {
    id: 'preferences',
    name: 'Preferences',
    description: 'User likes, dislikes, and preferences',
    keywords: ['like', 'prefer', 'favorite', 'hate', 'always', 'never'],
    prototypeQuery: 'prefer favorite like dislike always never habit',
    prefetchPriority: 5,
    defaultMemoryLimit: 25,
    decayRate: 0.1,
    relatedTopics: ['identity'],
  },
  {
    id: 'preferences/likes',
    parentId: 'preferences',
    name: 'Likes',
    description: 'Things the user likes',
    keywords: ['like', 'love', 'enjoy', 'favorite'],
    prototypeQuery: 'like love enjoy favorite prefer',
    prefetchPriority: 5,
    defaultMemoryLimit: 20,
    decayRate: 0.1,
    relatedTopics: ['preferences'],
  },
  {
    id: 'preferences/dislikes',
    parentId: 'preferences',
    name: 'Dislikes',
    description: 'Things the user dislikes',
    keywords: ['hate', 'dislike', 'avoid', 'never'],
    prototypeQuery: 'hate dislike avoid never refuse',
    prefetchPriority: 6,
    defaultMemoryLimit: 15,
    decayRate: 0.1,
    relatedTopics: ['preferences'],
  },

  // Identity
  {
    id: 'identity',
    name: 'Identity',
    description: 'Core user identity and background',
    keywords: ['i am', 'my name', 'about me'],
    prototypeQuery: 'identity who am background about myself',
    prefetchPriority: 8,
    defaultMemoryLimit: 30,
    decayRate: 0.05,
    relatedTopics: ['preferences', 'family'],
  },
  {
    id: 'identity/values',
    parentId: 'identity',
    name: 'Values',
    description: 'Personal values and beliefs',
    keywords: ['believe', 'value', 'important', 'principle'],
    prototypeQuery: 'value believe important principle philosophy',
    prefetchPriority: 7,
    defaultMemoryLimit: 15,
    decayRate: 0.05,
    relatedTopics: ['identity'],
  },
  {
    id: 'identity/background',
    parentId: 'identity',
    name: 'Background',
    description: 'Personal history and background',
    keywords: ['grew up', 'childhood', 'hometown', 'history'],
    prototypeQuery: 'background history grew up childhood hometown',
    prefetchPriority: 5,
    defaultMemoryLimit: 20,
    decayRate: 0.05,
    relatedTopics: ['identity', 'family'],
  },

  // Agent
  {
    id: 'agent',
    name: 'Agent',
    description: 'Agent-related topics',
    keywords: ['you', 'yourself', 'rook'],
    prototypeQuery: 'agent assistant you yourself',
    prefetchPriority: 4,
    defaultMemoryLimit: 15,
    decayRate: 0.1,
    relatedTopics: ['agent/self', 'agent/learnings'],
  },
  {
    id: 'agent/self',
    parentId: 'agent',
    name: 'Agent Self',
    description: 'Memories about the agent itself',
    keywords: ['about yourself', 'your', 'you remember'],
    prototypeQuery: 'agent self memory learned discovered about myself',
    prefetchPriority: 4,
    defaultMemoryLimit: 15,
    decayRate: 0.05,
    relatedTopics: ['agent/learnings'],
  },
  {
    id: 'agent/learnings',
    parentId: 'agent',
    name: 'Agent Learnings',
    description: 'Lessons and insights learned by the agent',
    keywords: ['learned', 'lesson', 'insight', 'discovered'],
    prototypeQuery: 'learned lesson insight discovered realization',
    prefetchPriority: 6,
    defaultMemoryLimit: 20,
    decayRate: 0.05,
    relatedTopics: ['agent/self', 'technical'],
  },

  // Conversation
  {
    id: 'conversation',
    name: 'Conversation',
    description: 'Previous conversation context',
    keywords: ['we talked', 'you said', 'last time', 'remember when'],
    prototypeQuery: 'conversation discussed talked mentioned said',
    prefetchPriority: 5,
    defaultMemoryLimit: 20,
    decayRate: 0.3,
    relatedTopics: ['history'],
  },
];
