//! Phase 1 fixture comparison test.
//!
//! Loads pre-computed reference embeddings (generated by scripts/fixture_gen.py
//! using sentence-transformers Python) and compares them against our Rust engine.
//! Asserts cosine similarity >= 0.999 per text per model.
//!
//! This test gates Phase 2: if any model's cosine delta is below the threshold,
//! the correctness fixes in Phase 1 are incomplete and Phase 2 must not proceed.
//!
//! Run with:
//!   cargo test --test fixture_comparison -- --ignored --nocapture

use engram_embed::embedder::{Embedder, ModelId};
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Fixture {
    model: String,
    texts: Vec<String>,
    embeddings: Vec<Vec<f32>>,
    #[serde(default)]
    prefix: Option<String>,
}

fn fixture_path(model_name: &str) -> PathBuf {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .join("tests")
        .join("fixtures")
        .join(format!("{}.json", model_name))
}

fn load_fixture(model_name: &str) -> Fixture {
    let path = fixture_path(model_name);
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Could not read fixture {}: {}", path.display(), e));
    serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("Could not parse fixture {}: {}", path.display(), e))
}

fn cosine_similarity(a: &[f32], b: &[f32]) -> f64 {
    assert_eq!(a.len(), b.len(), "dimension mismatch in cosine similarity");
    let dot: f64 = a.iter().zip(b.iter()).map(|(&x, &y)| x as f64 * y as f64).sum();
    let norm_a: f64 = a.iter().map(|&x| (x as f64) * (x as f64)).sum::<f64>().sqrt();
    let norm_b: f64 = b.iter().map(|&x| (x as f64) * (x as f64)).sum::<f64>().sqrt();
    if norm_a == 0.0 || norm_b == 0.0 {
        return 0.0;
    }
    dot / (norm_a * norm_b)
}

/// Compare one model's embeddings against reference fixtures.
/// Returns (min_cosine, avg_cosine) across all texts.
fn compare_model(model_id: ModelId, fixture_model_name: &str) -> (f64, f64) {
    let fixture = load_fixture(fixture_model_name);

    println!(
        "\n=== {} ({}) ===",
        fixture_model_name,
        model_id.to_hf_id()
    );
    println!("  {} texts, {} reference dims", fixture.texts.len(), fixture.embeddings[0].len());

    let embedder = Embedder::new(model_id)
        .unwrap_or_else(|e| panic!("Failed to load model {}: {}", fixture_model_name, e));

    // Embed all texts — Embedder applies the model's own prefix internally
    let ours = embedder
        .embed(&fixture.texts)
        .unwrap_or_else(|e| panic!("Embedding failed for {}: {}", fixture_model_name, e));

    assert_eq!(
        ours.len(),
        fixture.embeddings.len(),
        "output count mismatch for {}",
        fixture_model_name
    );

    let mut min_cos = f64::MAX;
    let mut sum_cos = 0.0;

    for (i, (ours_vec, ref_vec)) in ours.iter().zip(fixture.embeddings.iter()).enumerate() {
        let cos = cosine_similarity(ours_vec, ref_vec);
        if cos < min_cos {
            min_cos = cos;
        }
        sum_cos += cos;
        println!(
            "  [{:02}] cosine={:.6}  text: {}",
            i,
            cos,
            &fixture.texts[i][..fixture.texts[i].len().min(60)]
        );
    }

    let avg_cos = sum_cos / fixture.embeddings.len() as f64;
    println!("  MIN cosine: {:.6}  AVG cosine: {:.6}", min_cos, avg_cos);

    (min_cos, avg_cos)
}

const COSINE_THRESHOLD: f64 = 0.999;

#[test]
#[ignore = "requires model download — gates Phase 2"]
fn test_bge_base_fixture_comparison() {
    let (min_cos, avg_cos) = compare_model(ModelId::BgeBase, "bge-base");
    assert!(
        min_cos >= COSINE_THRESHOLD,
        "bge-base: min cosine {:.6} < threshold {:.3} (avg={:.6})",
        min_cos,
        COSINE_THRESHOLD,
        avg_cos
    );
}

#[test]
#[ignore = "requires model download — gates Phase 2"]
fn test_minilm_fixture_comparison() {
    let (min_cos, avg_cos) = compare_model(ModelId::MiniLM, "minilm");
    assert!(
        min_cos >= COSINE_THRESHOLD,
        "minilm: min cosine {:.6} < threshold {:.3} (avg={:.6})",
        min_cos,
        COSINE_THRESHOLD,
        avg_cos
    );
}

#[test]
#[ignore = "requires model download — gates Phase 2"]
fn test_gte_base_fixture_comparison() {
    let (min_cos, avg_cos) = compare_model(ModelId::GteBase, "gte-base");
    assert!(
        min_cos >= COSINE_THRESHOLD,
        "gte-base: min cosine {:.6} < threshold {:.3} (avg={:.6})",
        min_cos,
        COSINE_THRESHOLD,
        avg_cos
    );
}

#[test]
#[ignore = "requires model download — gates Phase 2"]
fn test_nomic_fixture_comparison() {
    let (min_cos, avg_cos) = compare_model(ModelId::Nomic, "nomic");
    assert!(
        min_cos >= COSINE_THRESHOLD,
        "nomic: min cosine {:.6} < threshold {:.3} (avg={:.6})",
        min_cos,
        COSINE_THRESHOLD,
        avg_cos
    );
}

/// Run all 4 models and report cosine deltas without asserting.
/// Useful for diagnostic comparison before Phase 2 gating.
#[test]
#[ignore = "requires all 4 model downloads"]
fn test_all_models_fixture_comparison_report() {
    let models = [
        (ModelId::BgeBase, "bge-base"),
        (ModelId::MiniLM, "minilm"),
        (ModelId::GteBase, "gte-base"),
        (ModelId::Nomic, "nomic"),
    ];

    let mut all_pass = true;
    let mut results = Vec::new();

    for (model_id, name) in &models {
        let (min_cos, avg_cos) = compare_model(*model_id, name);
        let pass = min_cos >= COSINE_THRESHOLD;
        if !pass {
            all_pass = false;
        }
        results.push((name, min_cos, avg_cos, pass));
    }

    println!("\n=== SUMMARY ===");
    println!("{:<12} {:>12} {:>12} {:>6}", "model", "min_cosine", "avg_cosine", "pass");
    for (name, min_cos, avg_cos, pass) in &results {
        println!(
            "{:<12} {:>12.6} {:>12.6} {:>6}",
            name,
            min_cos,
            avg_cos,
            if *pass { "YES" } else { "NO" }
        );
    }
    println!("threshold: {}", COSINE_THRESHOLD);

    assert!(
        all_pass,
        "One or more models failed cosine threshold — Phase 2 is blocked until fixed."
    );
}

