import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { MemoryWithScore } from '../../memory/memory.types';
import {
  AnticipatoryStrategy,
  ContextSignals,
  AnticipatoryResult,
} from './strategy.interface';

/**
 * Insight Injection Strategy
 *
 * Surfaces INSIGHT-layer memories generated by the Waking Cycle that are
 * relevant to the current query but haven't been surfaced recently.
 *
 * The Waking Cycle does the heavy lifting (pattern detection, LLM synthesis).
 * This strategy is the delivery mechanism — it gets those insights in front
 * of the agent when they're actually relevant.
 */
@Injectable()
export class InsightInjectionStrategy implements AnticipatoryStrategy {
  readonly name = 'insight_injection';
  private readonly logger = new Logger(InsightInjectionStrategy.name);

  /** Don't re-surface insights more than once every 4 hours. */
  private static readonly RESURFACE_COOLDOWN_MS = 4 * 60 * 60 * 1000;

  /** Decay factor per previous surfacing (reduces priority of over-shown insights). */
  private static readonly SURFACED_DECAY = 0.2;

  constructor(private readonly prisma: PrismaService) {}

  async execute(
    signals: ContextSignals,
    options: { maxResults: number; timeoutMs: number },
  ): Promise<AnticipatoryResult[]> {
    const deadline = Date.now() + options.timeoutMs;

    if (signals.topics.length === 0 && signals.entities.length === 0) {
      return [];
    }

    try {
      // Find INSIGHT-layer memories that haven't been recently surfaced
      const cooldownDate = new Date(
        Date.now() - InsightInjectionStrategy.RESURFACE_COOLDOWN_MS,
      );

      // Build topic/entity search terms for content matching
      const searchTerms = [...signals.topics, ...signals.entities];

      // Query insights — use raw content matching since insights don't have embeddings
      // optimized for the common case. We look for insights whose content or metadata
      // references our current topics/entities.
      const insights = await this.prisma.memory.findMany({
        where: {
          userId: signals.userId,
          layer: 'INSIGHT',
          deletedAt: null,
          supersededById: null,
          id: { notIn: [...signals.excludeMemoryIds] },
          // Don't return insights the user has explicitly acknowledged
          NOT: {
            metadata: {
              path: ['acknowledged'],
              equals: true,
            },
          },
        },
        include: { extraction: true },
        orderBy: [
          { confidence: 'desc' },
          { createdAt: 'desc' },
        ],
        take: 20, // Fetch more than needed, then score and filter
      });

      if (Date.now() > deadline) return [];

      // Score each insight by relevance to current signals
      const scored = insights
        .map((insight) => {
          const metadata = (insight.metadata as Record<string, any>) || {};
          const content = insight.raw.toLowerCase();
          const topics = (insight.extraction?.topics || []).map((t: string) => t.toLowerCase());

          // Topic/entity overlap score
          let relevanceScore = 0;
          for (const term of searchTerms) {
            const lower = term.toLowerCase();
            if (content.includes(lower)) relevanceScore += 0.3;
            if (topics.some((t: string) => t.includes(lower))) relevanceScore += 0.2;
          }

          // Freshness boost (newer insights more relevant)
          const ageDays = (Date.now() - insight.createdAt.getTime()) / (1000 * 60 * 60 * 24);
          const freshnessBoost = Math.max(0.1, 1 - ageDays / 14); // 14-day decay

          // Surfacing decay (shown too many times = lower priority)
          const surfacedCount = (metadata.surfacedCount as number) || 0;
          const surfacingDecay = Math.max(
            0.1,
            1 - surfacedCount * InsightInjectionStrategy.SURFACED_DECAY,
          );

          // Check surfacing cooldown
          const lastSurfaced = metadata.lastSurfacedAt
            ? new Date(metadata.lastSurfacedAt).getTime()
            : 0;
          if (lastSurfaced > cooldownDate.getTime()) {
            return null; // Still in cooldown
          }

          const confidence = insight.confidence ?? 0.5;
          const salience = relevanceScore * confidence * freshnessBoost * surfacingDecay;

          return { insight, salience, metadata };
        })
        .filter((r): r is NonNullable<typeof r> => r !== null && r.salience > 0)
        .sort((a, b) => b.salience - a.salience)
        .slice(0, options.maxResults);

      // Mark insights as surfaced (fire-and-forget, don't block response)
      for (const { insight, metadata } of scored) {
        this.markSurfaced(insight.id, metadata).catch((err) =>
          this.logger.warn(`Failed to mark insight ${insight.id} as surfaced: ${err.message}`),
        );
      }

      return scored.map(({ insight, salience, metadata }) => ({
        memory: { ...insight, score: salience } as MemoryWithScore,
        meta: {
          strategy: this.name,
          reason: 'Waking cycle insight relevant to current topic',
          salience,
          insightType: (metadata.insightType as string) || 'unknown',
        },
      }));
    } catch (err) {
      this.logger.warn(`Insight injection failed: ${(err as Error).message}`);
      return [];
    }
  }

  /**
   * Update surfacing metadata on the insight memory.
   * Fire-and-forget — doesn't block the recall response.
   */
  private async markSurfaced(
    memoryId: string,
    currentMetadata: Record<string, any>,
  ): Promise<void> {
    const surfacedCount = ((currentMetadata.surfacedCount as number) || 0) + 1;
    await this.prisma.memory.update({
      where: { id: memoryId },
      data: {
        metadata: {
          ...currentMetadata,
          surfacedCount,
          lastSurfacedAt: new Date().toISOString(),
        },
      },
    });
  }
}
